export const routes = {
  home: '/',
  create: '/create',
  chat: '/chat',
  mgc: '/mgc',
  search: '/search',
  signin: '/signin',
  mypage: '/mypage',
  changeMyInfo: '/mypage/change-my-info',
  likeMGC: '/mypage/like-mgc',
  currentJoinMGC: '/mypage/current-join-mgc',
  endJoinMGC: '/mypage/end-join-mgc',
  receivedReviews: '/mypage/end-join-mgc/received-reviews',
  sendReviews: '/mypage/end-join-mgc/send-reviews',
  receivedReviewsAssessment: '/mypage/received-reviews-assessment',
  reportList: '/mypage/report-list',
  blackList: '/mypage/black-list',
  withdrawal: '/mypage/withdrawal',
} as const;

export const titleMap = {
  chat: '채팅',
  create: '모각코 생성',
  mgc: '모각코 디테일',
  'edit-mgc': '모각코 수정',
  'current-join-mgc': '참여중인 모각코',
  'end-join-mgc': '종료된 모각코',
  'like-mgc': '내가 찜한 모각코',
  'received-reviews-assessment': '받은 리뷰 평가',
  'received-reviews': '받은 리뷰',
  'send-reviews': '보낸 리뷰',
  another: '프로필',
  'join-mgc': '참여한 모각코',
  'change-my-info': '개인정보 수정',
  'black-list': '블랙리스트',
  'report-list': '신고 목록',
} as const;
