import { ReactNode } from 'react';
import Navbar from '@/app/_components/NavBar';
import Provider from '@/app/_components/Provider';
import { Toaster } from '@/components/ui/toaster';
import { cn } from '@/libs/utils';
import '@/styles/globals.css';
import { getCategoryOptions } from '@/utils/getQueryOptions';
import { HydrationBoundary, QueryClient, dehydrate } from '@tanstack/react-query';
import type { Metadata } from 'next';
import localFont from 'next/font/local';
import Script from 'next/script';

const pretendard = localFont({
  src: '../../public/font/PretendardVariable.ttf',
  variable: '--pretendard',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = async ({
  children,
}: Readonly<{
  children: ReactNode;
}>) => {
  const queryClient = new QueryClient();
  await queryClient.prefetchQuery(getCategoryOptions());
  const dehydratedState = dehydrate(queryClient);

  return (
    <html lang="en">
      <body
        className={cn(pretendard.className, 'relative min-h-svh')}
        suppressHydrationWarning
      >
        <Script
          type="text/javascript"
          src={`//dapi.kakao.com/v2/maps/sdk.js?appkey=${process.env.NEXT_PUBLIC_KAKAO_MAP_KEY}&autoload=false&libraries=clusterer`}
          strategy="beforeInteractive"
        />
        <Provider>
          <main className="h-[calc(100vh-50px)]">
            <div className="overflow-y-auto px-20pxr scrollbar-hide">
              <HydrationBoundary state={dehydratedState}>{children}</HydrationBoundary>

              <div className="mb-50pxr" />
            </div>
          </main>
          <Navbar />
          <Toaster />
        </Provider>
      </body>
    </html>
  );
};

export default RootLayout;
